### ISSUE TITLE
Refresh on iOS

### ISSUE THREAD

**Issue by RejeanLabbe** [therealjohn/IncrementalListView#3]
Your plugin is great but I need to implement a "Refresh" feature and I am facing problems on iOS.

Maybe because the loading logic is initianalised in the "OnAppearing" event of the ContentPage, when I refresh the list, even if the "HasMoreItems" property has a value of "True", only the first "page" items are in the list.

There is no issue on Android.

**Comment by RejeanLabbe** [comment]
OK, I solved the issue by setting the "ListViewCachingStrategy" to "RetainElement" instead of "RecycleElement".

`<x:Arguments>
                    <ListViewCachingStrategy>RetainElement</ListViewCachingStrategy>
                </x:Arguments>`

**Comment by therealjohn** [comment]
You should be able to continue using RecycleElement. Changing to RetainElement is not recommended for performance reasons. What do you expect to happen when you Refresh?

I would expect the entire list to be cleared and N records loaded (limited by `PageSize`). Feel free to reopen.
