### ISSUE TITLE
Nothing appears on my xamarin.forms app 

### ISSUE THREAD

**Issue by tiagorodriguesnes** [therealjohn/IncrementalListView#4]
Can you give me a help on the ListView implementation?

I followed your code but my app is displaying nothing.

[Code.zip](https://github.com/therealjohn/IncrementalListView/files/2187849/Code.zip)

**Comment by therealjohn** [comment]
@2092015 You have some things set up incorrectly. The ` ItemsSource="{Binding Imoveis}"` means there should be a property in `IncrementalViewModel`. However, it appears you have this property inside the `ImovsPage`. This [documentation](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/data-bindings-to-mvvm) might help. Then you would set your page `BindingContext=new IncrementalViewModel()`, like [this](https://github.com/therealjohn/IncrementalListView/blob/master/Source/IncrementalListViewSample/IncrementalListViewSample/IncrementalListViewPage.xaml.cs#L17).
